### ISSUE TITLE
URLs are not turned into links in rendered markdown on the website

### ISSUE THREAD

**Issue by stof** [eufossa/symfony-hackathon-2019#17]
Github autolinks URL in markdown. But it looks like the markdown parser used to generate the link does not.

**Comment by jfhovinne** [comment]
Indeed. AFAIK this is a GitHub Pages limitation; we need to use `[]()`.

**Comment by stof** [comment]
OK, it looks like Github pages don't use GFM for their markdown, but kramdown. So here is what's necessary: https://kramdown.gettalong.org/syntax.html#automatic-links

**Comment by jfhovinne** [comment]
Thanks for the tip, @stof 
Closing this issue in favour of #28
